cam0:
  cam_bl: 1.0
  cam_width: 640
  cam_height: 480
  cam_model: Pinhole
  cam_fx: 570.3422241210938
  cam_fy: 570.3422241210938
  cam_cx: 319.5
  cam_cy: 239.5
  cam_d0: 0.0
  cam_d1: 0.0
  cam_d2: 0.0
  cam_d3: 0.0
images_subfolder_l: image_l/
images_subfolder_r: image_r/
